import { Crown, FileText, Shield, Star, Users } from 'lucide-react';
import type { WorkflowStep } from './types';

export const WORKFLOW_STEPS: WorkflowStep[] = [
  {
    id: 1,
    stageCode: 'SUBMISSION',
    titleTh: '1. พนักงานยื่นข้อร้องเรียน / ข้อเสนอแนะ',
    titleEn: 'Employee Voice Submission',
    shortDesc: 'พนักงานระบุตัวตน เลือกประเภท หมวดหมู่ กรอกรายละเอียด และแนบหลักฐาน',
    actorRole: 'employee',
    actorTitleTh: 'พนักงานผู้ยื่นเรื่อง (Employee)',
    actorColor: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    targetTab: 'submit',
    targetTabLabel: 'ยื่นข้อร้องเรียน / ข้อเสนอแนะ',
    durationEst: '1–3 นาที',
    keyActions: [
      'เลือกประเภทคำร้อง: "ข้อร้องเรียน (Complaint)" หรือ "ข้อเสนอแนะพัฒนา (Suggestion)"',
      'ระบุ 1 ใน 6 หมวดหมู่ที่เกี่ยวข้อง (HR, Compliance, Ethics, Fraud, Human Right/Harassment, Quality Impropriety)',
      'ประเมินระดับความเร่งด่วนและผลกระทบ (ต่ำ, ปานกลาง, เร่งด่วน, วิกฤติ)',
      'ตรวจสอบข้อมูลผู้ยื่นเรื่อง (ชื่อ-นามสกุล, รหัสพนักงาน, ฝ่าย, อีเมล) ซึ่งระบบเติมให้จากโปรไฟล์ HR ของบัญชีที่ล็อกอินด้วย SSO โดยส่งต่อเฉพาะ Gatekeeper ที่รับผิดชอบตามเกณฑ์ PDPA',
      'เลือกช่องทางส่งตรงถึงผู้บริหาร (CEO / EVP Direct Bypass) หากเป็นประเด็นอ่อนไหวหรือเร่งด่วนเป็นพิเศษ',
      'กรอกหัวข้อเรื่องใจความสำคัญ ระบุสถานที่/หน่วยงาน และรายละเอียดข้อเท็จจริงอย่างครบถ้วน',
      'แนบไฟล์หลักฐานได้ — ระบบอัปโหลดไฟล์จริงทันทีหลังสร้างคำร้อง หากไฟล์ใดอัปโหลดไม่สำเร็จ คำร้องยังคงอยู่ครบและกด "ลองแนบไฟล์อีกครั้ง" ได้',
    ],
    systemAutomations: [
      'ออกรหัสติดตามเฉพาะแบบถาวร (Tracking ID เช่น TK-2026-XXXX)',
      'วิเคราะห์ความรู้สึกและคัดกรองระดับความเร่งด่วนอัตโนมัติ (AI Sentiment & Priority Tagging)',
      'ส่งการแจ้งเตือน Real-time ยืนยันการรับเรื่องเข้ากล่องข้อความของผู้ยื่น (สถานะอ่าน/ยังไม่อ่านเป็นของแต่ละคน)',
      'ส่งอีเมลจริงผ่าน SMTP ของบริษัทถึง Lead Gatekeeper ของหมวดทันที (หากหมวดไม่มี Lead จะส่งไปอีเมลส่งต่อเรื่องของหน่วยงาน) — เปิด/ปิด แก้เทมเพลต ทดสอบส่ง และดูประวัติการส่งได้ในส่วน "Email Settings" ของหน้าจัดการผู้บริหาร & Gatekeeper',
      'ตัวตนของผู้ยื่นแบบนิรนามจะไม่ปรากฏในอีเมลถึง Gatekeeper และในประวัติการส่งอีเมล',
    ],
    rulesAndSla:
      'ข้อมูลส่วนบุคคลของผู้ยื่นได้รับการคุ้มครองตามมาตรฐาน PDPA ส่งต่อเฉพาะ Gatekeeper ที่รับผิดชอบโดยตรงเท่านั้น',
    icon: <FileText className="h-5 w-5 text-emerald-600" />,
  },
  {
    id: 2,
    stageCode: 'ROUTING',
    titleTh: '2. ระบบคัดแยกและจ่ายงานอัตโนมัติ',
    titleEn: 'Smart Dispatch & Auto-Routing',
    shortDesc: 'ส่งคำร้องไปยังหน่วยงานที่ถูกต้อง และจัดสรรผู้รับผิดชอบตามเกณฑ์ที่กำหนด',
    actorRole: 'admin',
    actorTitleTh: 'ระบบอัตโนมัติ / ผู้ดูแลระบบ (Admin)',
    actorColor: 'bg-slate-100 text-slate-700 border-slate-200',
    targetTab: 'admin_gatekeeper',
    targetTabLabel: 'กำหนด Gatekeeper แต่ละหน่วยงาน (Admin)',
    durationEst: 'ทันที (Real-time)',
    keyActions: [
      'คัดกรองหมวดหมู่และจับคู่กับทีม Gatekeeper ประจำฝ่ายที่รับผิดชอบ — Gatekeeper จะเห็นเรื่องนี้เมื่อเป็นเจ้าหน้าที่ของหมวดนั้น และหน้ากำหนดสิทธิ์เข้าถึง (RBAC) เปิดหมวดนั้นให้ Gatekeeper',
      'กระจายงานตามโหมดที่ Admin ตั้งค่าไว้ (Round Robin หมุนเวียน หรือ Workload Balanced กระจายตามภาระงานคงค้าง)',
      'ส่งการแจ้งเตือนงานใหม่ไปยังเจ้าหน้าที่ประจำฝ่ายทันที',
    ],
    systemAutomations: [
      'ส่งการแจ้งเตือนในระบบและอีเมลแจ้ง Lead Officer ประจำฝ่าย',
      'แจ้งเตือนระดับความสำคัญและความเร่งด่วนตามหมวดหมู่',
      'หากเลือก "CEO/EVP Direct Bypass" ระบบจะแจ้งเตือน Dashboard ผู้บริหารทันที',
    ],
    rulesAndSla: 'ระบบจัดสรรเคสอัตโนมัติทันทีตั้งแต่เคสถูกบันทึกสำเร็จเข้าระบบ',
    icon: <Users className="h-5 w-5 text-indigo-600" />,
  },
  {
    id: 3,
    stageCode: 'TRIAGE_ACTION',
    titleTh: '3. Gatekeeper ตรวจสอบและดำเนินการแก้ไข',
    titleEn: 'Triage, Investigation & Action Plan',
    shortDesc: 'เจ้าหน้าที่รับเรื่อง ตรวจสอบข้อเท็จจริง ดำเนินการแก้ไข และอัปเดตความคืบหน้า',
    actorRole: 'gatekeeper',
    actorTitleTh: 'เจ้าหน้าที่ Gatekeeper ประจำฝ่าย',
    actorColor: 'bg-indigo-50 text-indigo-700 border-indigo-200',
    targetTab: 'gatekeeper',
    targetTabLabel: 'Gatekeeper Triage Portal',
    durationEst: 'ตามลำดับความเร่งด่วนของเรื่อง',
    keyActions: [
      'กดรับเรื่อง (Accept / Triage) และระบุเจ้าหน้าที่ผู้รับผิดชอบหลัก',
      'เปลี่ยนสถานะเป็น "กำลังดำเนินการ (In Progress)" หรือ "กำลังตรวจสอบ (Investigating)"',
      'สื่อสารสองทางแบบนิรนาม (Anonymous 2-Way Chat): ซักถามและขอหลักฐานเพิ่มเติมจากผู้ร้องเรียนโดยที่ระบบรักษาการไม่เปิดเผยตัวตน 100%',
      'ดำเนินการแก้ไขปัญหาหน้างานจริง และจัดทำรายงานสรุปผลการสอบสวนข้อเท็จจริง (Official Investigation & CAPA Report)',
      'บันทึกสรุปผลการแก้ไข (Resolution Notes) และแนวทางป้องกันเชิงรุก (CAPA)',
      'เปิดดาวน์โหลดไฟล์แนบของผู้ยื่นได้จาก Timeline (เฉพาะคำร้องที่ตนมีสิทธิ์เห็น)',
    ],
    systemAutomations: [
      'บันทึก Audit Timeline Log ทุกครั้งที่มีการเปลี่ยนสถานะหรือส่งข้อความ',
      'ระบบแจ้งเตือนเคสค้างหรือมีความเร่งด่วนสูงไปยังเจ้าหน้าที่ผู้รับผิดชอบ',
      'ระบบออกรายงานสรุปผลการสอบสวนข้อเท็จจริง (Investigation Summary Report) พิมพ์/ส่งออกได้ทันที',
      'ส่งอีเมลจริงแจ้งผลการแก้ไขกลับไปยังพนักงานผู้ยื่นเรื่องทันทีเมื่อสถานะเปลี่ยนเป็น Resolved (ตามการเปิด/ปิดในการตั้งค่าอีเมล)',
    ],
    rulesAndSla:
      'เจ้าหน้าที่ต้องระบุแนวทางและผลการแก้ไขที่ชัดเจน พร้อมทั้งสามารถจัดทำรายงานสรุปผลการสอบสวนก่อนกดยืนยันปิดเคส (Resolved)',
    icon: <Shield className="h-5 w-5 text-indigo-600" />,
  },
  {
    id: 4,
    stageCode: 'FEEDBACK_LOOP',
    titleTh: '4. ติดตามผลและประเมินความพึงพอใจ (CSAT)',
    titleEn: 'Employee Tracking & CSAT Evaluation',
    shortDesc: 'พนักงานตรวจสอบผลการแก้ไข ให้คะแนนความพึงพอใจ ยืนยันการแก้ไขปัญหา และปิดเคส',
    actorRole: 'employee',
    actorTitleTh: 'พนักงานผู้ยื่นเรื่อง (Employee)',
    actorColor: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    targetTab: 'my_tickets',
    targetTabLabel: 'ติดตามสถานะเรียลไทม์ (Timeline)',
    durationEst: '1–2 วันหลังปิดเคส',
    keyActions: [
      'ตรวจสอบผลการแก้ไขและการดำเนินงานผ่าน Interactive Timeline ดาวน์โหลดไฟล์แนบของคำร้อง และเปิดดูรายงานผลการสอบสวน (Official Report)',
      'โต้ตอบหรือส่งข้อคิดเห็นเพิ่มเติมผ่านระบบสื่อสารสองทางแบบนิรนาม (Anonymous 2-Way Chat)',
      'ทำแบบประเมิน CSAT ใหม่ 4 ข้อ: 1. ปัญหาได้รับการแก้ไข (ใช่ / ไม่ใช่) 2. ความคิดเห็นเพิ่มเติม 3. ข้อเสนอแนะเพื่อพัฒนาองค์กร และ 4. ความพึงพอใจภาพรวมทั้งหมด (1–5 ดาว)',
      'กดยืนยันปิดเคสสมบูรณ์ (Status: Closed) อย่างเป็นทางการ',
    ],
    systemAutomations: [
      'คำนวณคะแนน CSAT รวมและอัปเดตสถิติเข้า Dashboard หน่วยงานทันที',
      'ปิดเคสสมบูรณ์ (Status: Closed) หลังได้รับการประเมินความพึงพอใจ',
    ],
    rulesAndSla: 'ผลคะแนน CSAT ถูกนำไปคำนวณ KPI ประจำหน่วยงานเพื่อความโปร่งใสและสร้างมาตรฐานบริการ',
    icon: <Star className="h-5 w-5 text-amber-500" />,
  },
  {
    id: 5,
    stageCode: 'EXECUTIVE_AI',
    titleTh: '5. ผู้บริหารวิเคราะห์ภาพรวม & AI จัดกลุ่มต้นตอ',
    titleEn: 'Executive Oversight & AI Root Cause Analytics',
    shortDesc: 'วิเคราะห์อัตราแก้ไขสำเร็จ, CSAT และใช้ AI จัดกลุ่มป้องกันเชิงรุก (CAPA)',
    actorRole: 'executive',
    actorTitleTh: 'ผู้บริหารระดับสูง (CEO / EVP / GRC)',
    actorColor: 'bg-purple-50 text-purple-700 border-purple-200',
    targetTab: 'executive',
    targetTabLabel: 'Dashboard & AI CAPA',
    durationEst: 'เรียลไทม์ / ประจำสัปดาห์ / ประจำเดือน',
    keyActions: [
      'ติดตามมาตรวัดหลัก: Total Tickets, Resolution Rate %, Average CSAT Score',
      'ดูสถิติแยกตาม 6 หน่วยงาน และตรวจสอบเคสด่วนพิเศษ (CEO/EVP Bypass)',
      'ใช้ระบบ AI Clustering เพื่อจัดกลุ่มปัญหาที่เกิดซ้ำๆ (Root Cause Analysis 4M)',
      'กำหนดนโยบายและมาตรการป้องกันเชิงรุกระดับองค์กร (CAPA Action Plan)',
    ],
    systemAutomations: [
      'AI สกัด Insights และวิเคราะห์สาเหตุเชิงโครงสร้าง (People, Process, Equipment, Governance)',
      'ระบบแจ้งเตือน Executive Alert เมื่อมีเคสความเสี่ยงสูงหรือข้อร้องเรียนคั่งค้าง',
    ],
    rulesAndSla:
      'ข้อมูลสรุปภาพรวมส่งออกเป็นไฟล์ Excel CSV / JSON ได้ และ HR Admin ใช้ SQL Query Studio ในเมนูส่งออกรันรายงานสำเร็จรูป 5 รายการบนฐานข้อมูลจริงได้ โดยครอบคลุมเฉพาะคำร้องที่ผู้ดูมีสิทธิ์เห็น (ไม่สามารถเขียน SQL เองได้)',
    icon: <Crown className="h-5 w-5 text-purple-600" />,
  },
];
