// src/services/rosterDefaults.ts — upstream's demo rosters, tab catalogue and RBAC matrix defaults.
// Pure data (no browser storage) so Server Actions (reset*ToDefault) and the seed can import it;
// src/services/api.ts re-exports it for the upstream components.
import type {
  ExecutiveMember,
  HrAdminMember,
  RolePermissionConfig,
  TabDefinition,
  UserRole,
} from '../types';

export const INITIAL_EXECUTIVES: ExecutiveMember[] = [
  {
    id: 'exec-1',
    name: 'คุณประเสริฐ อัครเดชานนท์',
    position: 'ประธานเจ้าหน้าที่บริหาร (Chief Executive Officer - CEO)',
    department: 'สำนักประธานเจ้าหน้าที่บริหาร (Office of the CEO)',
    email: 'prasert.ceo@enterprise.co.th',
    phone: '02-998-1001',
    roleType: 'CEO',
    isPrimaryWhistleblowerReceiver: true,
    canViewConfidentialIdentities: true,
    receiveAlertNotifications: true,
    assignedCommittees: ['คณะกรรมการบริหารระดับสูง (ExCom)', 'คณะกรรมการจริยธรรมองค์กร'],
    status: 'active',
    updatedAt: '2026-08-28T08:00:00.000Z',
  },
  {
    id: 'exec-2',
    name: 'ดร.กานดา รัตนพาณิชย์',
    position:
      'รองกรรมการผู้จัดการใหญ่อาวุโส สายงานบรรษัทภิบาลและความยั่งยืน (Senior EVP Governance & GRC)',
    department: 'Corporate Governance & Risk Oversight Group',
    email: 'kanda.r@enterprise.co.th',
    phone: '02-998-1002',
    roleType: 'EVP',
    isPrimaryWhistleblowerReceiver: true,
    canViewConfidentialIdentities: true,
    receiveAlertNotifications: true,
    assignedCommittees: ['คณะกรรมการกำกับดูแลการทุจริตและจริยธรรม', 'คณะกรรมการบริหารความเสี่ยง'],
    status: 'active',
    updatedAt: '2026-08-28T08:00:00.000Z',
  },
  {
    id: 'exec-3',
    name: 'คุณธีรภัทร เอกวิริยะ',
    position: 'ประธานคณะกรรมการตรวจสอบและธรรมาภิบาล (Audit Committee Chair)',
    department: 'คณะกรรมการตรวจสอบอิสระ (Independent Audit Committee)',
    email: 'theeraphat.audit@enterprise.co.th',
    phone: '02-998-1003',
    roleType: 'Audit_Committee',
    isPrimaryWhistleblowerReceiver: true,
    canViewConfidentialIdentities: false,
    receiveAlertNotifications: true,
    assignedCommittees: ['คณะกรรมการตรวจสอบภายใน', 'คณะกรรมการสอบสวนทางวินัยร้ายแรง'],
    status: 'active',
    updatedAt: '2026-08-28T08:00:00.000Z',
  },
  {
    id: 'exec-4',
    name: 'คุณศิรินทร์ รัตนดิลก',
    position: 'ผู้ช่วยกรรมการผู้จัดการใหญ่ สายงานทรัพยากรบุคคล (Chief People Officer - CPO)',
    department: 'People & Culture Corporate Group',
    email: 'sirin.r@enterprise.co.th',
    phone: '02-998-1004',
    roleType: 'EVP',
    isPrimaryWhistleblowerReceiver: false,
    canViewConfidentialIdentities: false,
    receiveAlertNotifications: true,
    assignedCommittees: [
      'คณะกรรมการบริหารระดับสูง (ExCom)',
      'คณะกรรมการแรงงานสัมพันธ์และสวัสดิการ',
    ],
    status: 'active',
    updatedAt: '2026-08-28T08:00:00.000Z',
  },
];

export const INITIAL_HR_ADMINS: HrAdminMember[] = [
  {
    id: 'admin-1',
    name: 'คุณชิดชนก วงศ์ประเสริฐ',
    position:
      'ผู้อำนวยการฝ่ายทรัพยากรบุคคลและตัวแทนผู้บริหาร (HR Director & Executive Representative)',
    department: 'People & Organization Strategy Division',
    email: 'chidchanok.w@enterprise.co.th',
    phone: '02-998-2001',
    roleLevel: 'super_admin',
    canManageRbac: true,
    canManageGatekeepers: true,
    canManageExecutives: true,
    receiveSystemAlerts: true,
    status: 'active',
    updatedAt: '2026-08-28T08:00:00.000Z',
  },
  {
    id: 'admin-2',
    name: 'คุณเอกชัย ศิริสมบัติ',
    position:
      'ผู้จัดการฝ่ายแรงงานสัมพันธ์และข้อร้องเรียนพนักงาน (Employee Relations & Grievance Manager)',
    department: 'Employee Relations & Staff Engagement Unit',
    email: 'ekachai.s@enterprise.co.th',
    phone: '02-998-2002',
    roleLevel: 'hr_manager',
    canManageRbac: true,
    canManageGatekeepers: true,
    canManageExecutives: false,
    receiveSystemAlerts: true,
    status: 'active',
    updatedAt: '2026-08-28T08:00:00.000Z',
  },
  {
    id: 'admin-3',
    name: 'คุณธนกฤต เมธีธรรม',
    position: 'ผู้เชี่ยวชาญอาวุโสด้านการปฏิบัติตามกฎเกณฑ์ (Senior GRC & Compliance Specialist)',
    department: 'Corporate Governance & Internal Compliance Group',
    email: 'thanakrit.m@enterprise.co.th',
    phone: '02-998-2003',
    roleLevel: 'compliance_auditor',
    canManageRbac: false,
    canManageGatekeepers: true,
    canManageExecutives: false,
    receiveSystemAlerts: true,
    status: 'active',
    updatedAt: '2026-08-28T08:00:00.000Z',
  },
  {
    id: 'admin-4',
    name: 'คุณสุชาดา พิพัฒน์ธนากุล',
    position: 'ผู้ดูแลระบบสารสนเทศบุคคลและสิทธิ์การเข้าถึง (HRIS & System Access Administrator)',
    department: 'HR Digital Operations & Systems Unit',
    email: 'suchada.p@enterprise.co.th',
    phone: '02-998-2004',
    roleLevel: 'super_admin',
    canManageRbac: true,
    canManageGatekeepers: true,
    canManageExecutives: true,
    receiveSystemAlerts: true,
    status: 'active',
    updatedAt: '2026-08-28T08:00:00.000Z',
  },
];

export const APP_TABS: TabDefinition[] = [
  {
    id: 'submit',
    nameTh: 'ยื่นข้อร้องเรียน',
    nameEn: 'Submit Grievance',
    descriptionTh: 'ฟอร์มส่งข้อร้องเรียน/ข้อเสนอแนะ พร้อมระบบ AI ช่วยคัดกรองและประเมินความเสี่ยง',
    category: 'core',
    iconName: 'FileText',
    defaultRoles: ['employee', 'admin'],
  },
  {
    id: 'my_tickets',
    nameTh: 'ติดตามสถานะ & คำร้องของฉัน',
    nameEn: 'My Submissions & Tracking',
    descriptionTh: 'ตรวจสอบสถานะคำร้อง ดู Timeline การดำเนินงาน และประเมินความพึงพอใจ CSAT',
    category: 'core',
    iconName: 'ListChecks',
    defaultRoles: ['employee', 'gatekeeper', 'admin'],
  },
  {
    id: 'workflow',
    nameTh: 'คู่มือและเกณฑ์มาตรฐาน',
    nameEn: 'Manual & Governance Guidelines',
    descriptionTh: 'ผังขั้นตอนการทำงาน (Workflow), เกณฑ์ความปลอดภัย PDPA และนโยบายคุ้มครองพนักงาน',
    category: 'core',
    iconName: 'GitBranch',
    defaultRoles: ['employee', 'gatekeeper', 'executive', 'admin'],
  },
  {
    id: 'gatekeeper',
    nameTh: 'ศูนย์รับเรื่องและคัดกรอง (Gatekeeper Inbox)',
    nameEn: 'Gatekeeper Triage Inbox',
    descriptionTh: 'กล่องรับเรื่องและมอบหมายงานเฉพาะหน่วยงานที่รับผิดชอบ บันทึกสืบสวนและแผนแก้ไข',
    category: 'operations',
    iconName: 'Shield',
    defaultRoles: ['gatekeeper', 'admin'],
  },
  {
    id: 'executive',
    nameTh: 'Dashboard',
    nameEn: 'Executive Dashboard & Whistleblower',
    descriptionTh:
      'แดชบอร์ดสรุปผลเชิงวิเคราะห์ระดับผู้บริหาร (CEO/EVP) 6 หมวดหมู่, สาเหตุหลัก, CSAT และสายตรง',
    category: 'executive',
    iconName: 'Crown',
    defaultRoles: ['executive', 'admin'],
  },
  {
    id: 'clustering',
    nameTh: 'วิเคราะห์สาเหตุ CAPA',
    nameEn: 'Root Cause & CAPA Clustering',
    descriptionTh:
      'การจัดกลุ่มปัญหาซ้ำซ้อน วิเคราะห์สาเหตุเชิงลึก (Root Cause) และมาตรการป้องกันเชิงรุก',
    category: 'executive',
    iconName: 'Layers',
    defaultRoles: ['executive', 'admin'],
  },
  {
    id: 'admin_gatekeeper',
    nameTh: 'จัดการผู้บริหาร, Admin & Gatekeeper',
    nameEn: 'Personnel & Governance Directory',
    descriptionTh:
      'Maintain รายชื่อคณะผู้บริหารระดับสูง (CEO/EVP Whistleblower Channel), ทีมงาน HR Admin และผู้รับผิดชอบ 6 ฝ่ายงาน',
    category: 'administration',
    iconName: 'Users',
    defaultRoles: ['admin'],
  },
  {
    id: 'rbac_management',
    nameTh: 'กำหนดสิทธิ์การเข้าถึง (RBAC)',
    nameEn: 'Role-Based Access Management',
    descriptionTh:
      'ศูนย์ควบคุมสิทธิ์ (HR Admin & ตัวแทนผู้บริหาร) กำหนดสิทธิ์การมองเห็นและขอบเขตหมวดหมู่คำร้องของแต่ละ Role',
    category: 'administration',
    iconName: 'SlidersHorizontal',
    defaultRoles: ['admin'],
  },
  {
    id: 'admin_users',
    nameTh: 'จัดการผู้ใช้ (SSO)',
    nameEn: 'User Management (SSO)',
    descriptionTh:
      'กำหนดบทบาทให้ผู้ใช้ที่เข้าสู่ระบบผ่าน SSO (พนักงาน / Gatekeeper / ผู้บริหาร / Admin)',
    category: 'administration',
    iconName: 'UserCog',
    defaultRoles: ['admin'],
  },
  {
    id: 'admin_audit_logs',
    nameTh: 'บันทึกการใช้งานระบบ',
    nameEn: 'System Audit Logs',
    descriptionTh: 'ประวัติการเข้าสู่ระบบและการเปลี่ยนแปลงสิทธิ์ของผู้ใช้ทั้งหมด',
    category: 'administration',
    iconName: 'ScrollText',
    defaultRoles: ['admin'],
  },
];

export const INITIAL_ROLE_PERMISSIONS: Record<UserRole, RolePermissionConfig> = {
  employee: {
    role: 'employee',
    roleTitleTh: 'พนักงานทั่วไป (General Employee)',
    roleTitleEn: 'General Employee',
    descriptionTh:
      'ผู้ใช้งานทั่วไป สามารถยื่นข้อร้องเรียน/ข้อเสนอแนะ ติดตามสถานะคำร้องของตนเอง และศึกษาคู่มือเกณฑ์มาตรฐาน',
    badgeColor: 'bg-blue-50 text-blue-700 border-blue-200',
    allowedTabs: ['submit', 'my_tickets', 'workflow'],
    canViewAllDepartments: false,
    assignedDepartments: [],
    canViewDirectCeoTickets: false,
    canViewConfidentialIdentities: false,
    canViewAnonymousSubmitterEmail: false,
    canEditRootCauseAndCapa: false,
    canManageGatekeeperOfficers: false,
    canManageRolePermissions: false,
  },
  gatekeeper: {
    role: 'gatekeeper',
    roleTitleTh: 'ผู้ประสานงานหน่วยงาน (Gatekeeper)',
    roleTitleEn: 'Department Gatekeeper',
    descriptionTh:
      'เจ้าหน้าที่ผู้รับผิดชอบประจำหน่วยงาน คัดกรอง สืบสวน และส่งต่อแก้ไขตามสายงานที่เกี่ยวข้อง',
    badgeColor: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    allowedTabs: ['gatekeeper', 'my_tickets', 'workflow'],
    canViewAllDepartments: true,
    assignedDepartments: ['HR', 'Compliance', 'Ethics', 'Fraud', 'Harassment', 'Quality'],
    canViewDirectCeoTickets: false,
    canViewConfidentialIdentities: false,
    canViewAnonymousSubmitterEmail: false,
    canEditRootCauseAndCapa: true,
    canManageGatekeeperOfficers: false,
    canManageRolePermissions: false,
  },
  executive: {
    role: 'executive',
    roleTitleTh: 'ผู้บริหารระดับสูง (CEO / EVP / GRC)',
    roleTitleEn: 'Executive & Governance Board',
    descriptionTh:
      'ผู้บริหารและคณะกรรมการกำกับดูแล เข้าถึงแดชบอร์ดภาพรวม กล่องข้อร้องเรียนสายตรง Whistleblower และการวิเคราะห์ CAPA',
    badgeColor: 'bg-purple-50 text-purple-700 border-purple-200',
    allowedTabs: ['executive', 'clustering', 'workflow'],
    canViewAllDepartments: true,
    assignedDepartments: [],
    canViewDirectCeoTickets: true,
    canViewConfidentialIdentities: false,
    canViewAnonymousSubmitterEmail: true,
    canEditRootCauseAndCapa: true,
    canManageGatekeeperOfficers: false,
    canManageRolePermissions: false,
  },
  admin: {
    role: 'admin',
    roleTitleTh: 'HR Administrator & ตัวแทนผู้บริหาร',
    roleTitleEn: 'HR Admin & Executive Representative',
    descriptionTh:
      'ผู้ดูแลระบบสูงสุดและตัวแทนฝ่ายบริหาร มีสิทธิ์เข้าถึงทุกฟังก์ชัน กำหนดสิทธิ์ RBAC และจัดสรรผู้รับผิดชอบหน่วยงาน',
    badgeColor: 'bg-rose-50 text-rose-700 border-rose-200',
    allowedTabs: [
      'submit',
      'my_tickets',
      'workflow',
      'gatekeeper',
      'executive',
      'clustering',
      'admin_gatekeeper',
      'rbac_management',
      'admin_users',
      'admin_audit_logs',
    ],
    canViewAllDepartments: true,
    assignedDepartments: [],
    canViewDirectCeoTickets: true,
    canViewConfidentialIdentities: true,
    canViewAnonymousSubmitterEmail: true,
    canEditRootCauseAndCapa: true,
    canManageGatekeeperOfficers: true,
    canManageRolePermissions: true,
  },
};
