import {
  CategoryInfo,
  ComplaintTicket,
  DepartmentGatekeeperConfig,
  GrievanceCategory,
  NotificationItem,
} from './types';

export const CATEGORY_DEFINITIONS: Record<GrievanceCategory, CategoryInfo> = {
  HR: {
    key: 'HR',
    nameTh: 'HR – ทรัพยากรบุคคลและสวัสดิการ',
    nameEn: 'HR – Human Resources & Employee Benefits',
    descriptionTh:
      'ค่าตอบแทน, สวัสดิการพนักงาน, เวลาการทำงาน, การโยกย้ายตำแหน่ง, การประเมินผลงาน, สิทธิประโยชน์ และความสัมพันธ์แรงงาน',
    responsibleDept: 'People & Culture Department (ฝ่ายบริหารทรัพยากรบุคคล)',
    badgeColor: 'bg-blue-50 text-blue-700 border-blue-200',
    iconName: 'Users',
  },
  Compliance: {
    key: 'Compliance',
    nameTh: 'Compliance – การไม่ปฏิบัติตามกฎหมายและกฎเกณฑ์',
    nameEn: 'Compliance – Regulatory & Legal Rules',
    descriptionTh:
      'การไม่ปฏิบัติตามกฎหมายและกฎเกณฑ์ (เช่น กฎหมายควบคุมแข่งขันทางการค้า (Competition Laws), กฎหมายและข้อบังคับว่าด้วยการควบคุมการส่งออกเพื่อนโยบายความมั่นคง (National Security Export Controls), พระราชบัญญัติคุ้มครองข้อมูลส่วนบุคคล (PDPA), กฎหมายแรงงาน และระเบียบข้อบังคับทางกฎหมายภายนอก)',
    responsibleDept: 'Governance, Risk & Compliance Division (ฝ่ายกำกับดูแลและกฎหมาย)',
    badgeColor: 'bg-indigo-50 text-indigo-700 border-indigo-200',
    iconName: 'FileCheck2',
  },
  Ethics: {
    key: 'Ethics',
    nameTh: 'Ethics – จริยธรรม',
    nameEn: 'Ethics – Corporate Ethics & Business Conduct',
    descriptionTh:
      'จริยธรรม (การฟอกเงิน, การซื้อขายหลักทรัพย์โดยใช้ข้อมูลภายใน, ข้องเกี่ยวกับกลุ่มผู้มีอิทธิพลซึ่งไม่ชอบด้วยกฎหมาย, กิจกรรมทางการเมืองและสังคม, การบริหารจัดการทรัพย์สินที่มีรูปร่างและไม่มีรูปร่างของบริษัท (ข้อมูลความลับ ทรัพย์สินทางปัญญา ฯลฯ), การจัดการและเปิดเผยข้อมูลของบริษัท, การละเมิดสิทธิในทรัพย์สินทางปัญญา (สิทธิบัตร ลิขสิทธิ์ เครื่องหมายการค้า) ของบุคคลที่สาม, การบันทึกและรายงานทางการเงิน, การให้ข้อมูลเกี่ยวกับกลุ่มบริษัท UBE แก่สังคมภายนอกและโพสต์ข้อมูลบนอินเทอร์เน็ต)',
    responsibleDept: 'Ethics Committee & Corporate Governance (คณะกรรมการจริยธรรมองค์กร)',
    badgeColor: 'bg-purple-50 text-purple-700 border-purple-200',
    iconName: 'Scale',
  },
  Fraud: {
    key: 'Fraud',
    nameTh: 'Fraud – การทุจริต และการฉ้อโกง',
    nameEn: 'Fraud – Anti-Fraud & Anti-Corruption',
    descriptionTh:
      'การทุจริต และการฉ้อโกง (การฉ้อโกง/การทุจริตทางการเงิน, การคอร์รัปชัน/การติดสินบน, การทำธุรกรรมที่มีผลประโยชน์ทับซ้อน, รับของขวัญหรือการรับรองที่มากเกินขอบเขต, การปลอมแปลงเอกสาร และการยักยอกทรัพย์สิน)',
    responsibleDept: 'Internal Audit & Forensic Investigation (ฝ่ายตรวจสอบภายในและการสอบสวนทุจริต)',
    badgeColor: 'bg-red-50 text-red-700 border-red-200',
    iconName: 'FileWarning',
  },
  Harassment: {
    key: 'Harassment',
    nameTh: 'Human Right , Harassment – สิทธิมนุษยชน , การล่วงละเมิด',
    nameEn: 'Human Right , Harassment – Human Rights & Anti-Harassment',
    descriptionTh:
      'สิทธิมนุษยชน, การล่วงละเมิด, การเลือกปฏิบัติ, การคุกคามทางเพศ (Sexual Harassment), การกลั่นแกล้งข่มขู่ในที่ทำงาน (Workplace Bullying) และการกระทำอันละเมิดต่อศักดิ์ศรีความเป็นมนุษย์',
    responsibleDept:
      'Human Rights & Grievance Panel (คณะกรรมการคุ้มครองสิทธิมนุษยชนและสุขภาวะพนักงาน)',
    badgeColor: 'bg-rose-50 text-rose-700 border-rose-200',
    iconName: 'AlertOctagon',
  },
  Quality: {
    key: 'Quality',
    nameTh: 'Quality Impropriety – การตรวจสอบคุณภาพอย่างไม่เหมาะสม',
    nameEn: 'Quality Impropriety – Quality Assurance & Standards',
    descriptionTh:
      'การตรวจสอบคุณภาพอย่างไม่เหมาะสม (เช่น การบิดเบือนหรือแก้ไขผลการทดสอบคุณภาพสินค้า/วัตถุดิบ, การละเลยขั้นตอนและมาตรฐาน QA/QC, การปล่อยผ่านสินค้าที่ไม่ผ่านเกณฑ์มาตรฐาน, การส่งมอบงานตกหล่น และการปลอมแปลงใบรับรองคุณภาพ)',
    responsibleDept: 'Operational Excellence & Quality Assurance (ฝ่ายประกันคุณภาพและการปรับปรุง)',
    badgeColor: 'bg-emerald-50 text-emerald-700 border-emerald-200',
    iconName: 'CheckCircle2',
  },
};

export const INITIAL_COMPLAINTS: ComplaintTicket[] = [
  {
    id: 'tk-3',
    trackingCode: 'TK-2026-0879',
    type: 'suggestion',
    category: 'HR',
    title:
      'ข้อเสนอแนะ: จัดตั้งโปรแกรม Flexible Benefits และวันลาเพื่อสุขภาพจิต (Mental Health Day)',
    description:
      'เสนอให้ฝ่าย HR เพิ่มความยืดหยุ่นในแพ็กเกจสวัสดิการ เช่น นำวงเงินค่ารักษาพยาบาลคงเหลือไปแลกเป็นคอร์สฟิตเนส หรือการตรวจสุขภาพเฉพาะทาง และเพิ่มวันลา Mental Wellness 2 วันต่อปี',
    locationOrUnit: 'ทุกหน่วยงาน (Corporate-wide)',
    isDirectToExecutive: true,
    confidentiality: 'standard_named',
    submitterName: 'ชลธิชา รัตนไพบูลย์',
    submitterEmployeeId: 'EMP-1823',
    submitterDepartment: 'Strategic Marketing & Brand',
    submitterEmail: 'chonticha.r@company.internal',
    gatekeeperDepartment: 'People & Culture Department',
    assignedOfficerName: 'ภานุมาศ สัจจาภิรมย์ (Head of Total Rewards)',
    assignedOfficerEmail: 'panumas.s@company.internal',
    status: 'closed',
    urgency: 'Medium',
    riskSeverity: 'Low',
    sentiment: 'Constructive',
    clusterGroup: 'Employee Wellbeing & Benefits Enhancement',
    rootCauseCategory: 'Policy/Governance',
    rootCauseSummary: 'สวัสดิการเดิมเป็นแบบตายตัว ไม่ตอบโจทย์ความหลากหลายของช่วงวัยพนักงาน',
    preventiveActionPlan:
      'บรรจุเข้าสู่วาระพิจารณาแผนสวัสดิการประจำปี 2027 และนำร่องโครงการ Flexible Points ใน Q1',
    resolutionSummary:
      'ฝ่ายบริหารและ HR พิจารณาเห็นชอบในหลักการ โดยจะเริ่มนำร่องระบบ Flex-Points ในไตรมาสที่ 1 ปีหน้า และอนุมัติวัน Wellness Leave เพิ่มเติม 1 วันในนโยบายใหม่',
    resolvedAt: '2026-08-25T14:30:00.000Z',
    closedAt: '2026-08-26T09:00:00.000Z',
    evaluation: {
      id: 'eval-1',
      ticketId: 'tk-3',
      overallScore: 5,
      speedRating: 5,
      resolutionQualityRating: 5,
      serviceMannerRating: 5,
      clarityRating: 5,
      isResolvedPermanently: true,
      feedbackComment:
        'ประทับใจมากที่ฝ่ายบริหารและ HR นำข้อเสนอแนะของพนักงานไปพิจารณาปรับใช้อย่างเป็นรูปธรรมและรวดเร็ว ขอบคุณที่เปิดรับฟังเสียงพนักงานค่ะ',
      improvementSuggestions:
        'อยากให้มีการอัปเดตความคืบหน้าระบบ Flex-Points ผ่าน Townhall ครั้งต่อไปด้วยค่ะ',
      evaluatedAt: '2026-08-26T09:00:00.000Z',
    },
    attachments: [
      {
        id: 'att-5',
        name: 'flexible_benefits_benchmark_proposal.pdf',
        size: '3.1 MB',
        type: 'application/pdf',
      },
    ],
    timeline: [
      {
        id: 'tl-31',
        timestamp: '2026-08-22T10:00:00.000Z',
        actor: 'ชลธิชา รัตนไพบูลย์',
        actorRole: 'Employee',
        action: 'ยื่นข้อเสนอแนะเพื่อการพัฒนาองค์กร',
        status: 'submitted',
      },
      {
        id: 'tl-32',
        timestamp: '2026-08-22T14:00:00.000Z',
        actor: 'HR Gatekeeper',
        actorRole: 'Gatekeeper',
        action: 'รับเรื่องและส่งต่อฝ่ายสิทธิประโยชน์',
        status: 'gatekeeper_triaged',
      },
      {
        id: 'tl-33',
        timestamp: '2026-08-24T09:00:00.000Z',
        actor: 'ภานุมาศ สัจจาภิรมย์',
        actorRole: 'Assigned Officer',
        action: 'นำเสนอในที่ประชุม HR Strategy Committee',
        status: 'in_progress',
      },
      {
        id: 'tl-34',
        timestamp: '2026-08-25T14:30:00.000Z',
        actor: 'ภานุมาศ สัจจาภิรมย์',
        actorRole: 'Assigned Officer',
        action: 'แจ้งผลการอนุมัติและแนวทางดำเนินการ',
        status: 'resolved',
      },
      {
        id: 'tl-35',
        timestamp: '2026-08-26T09:00:00.000Z',
        actor: 'ชลธิชา รัตนไพบูลย์',
        actorRole: 'Employee',
        action: 'ประเมินความพึงพอใจ 5 ดาว และปิดเรื่อง',
        status: 'closed',
      },
    ],
    anonymousMessages: [
      {
        id: 'chat-m4',
        ticketId: 'tk-3',
        senderRole: 'gatekeeper',
        senderDisplayName: 'ภานุมาศ สัจจาภิรมย์ (Head of Total Rewards)',
        message:
          'สวัสดีครับคุณพนักงาน ทางทีมงาน Total Rewards ได้รับข้อเสนอแนะเรื่อง Flexible Benefits แล้ว และได้นำเข้าหารือในที่ประชุม HR Strategy Committee ในเบื้องต้นแล้วครับ',
        timestamp: '2026-08-23T11:00:00.000Z',
        isStaff: true,
        isReadByEmployee: true,
        isReadByStaff: true,
      },
      {
        id: 'chat-m5',
        ticketId: 'tk-3',
        senderRole: 'employee',
        senderDisplayName: 'ผู้ยื่นข้อเสนอแนะ (Employee)',
        message:
          'ขอบคุณมากครับ หากต้องการข้อมูล Benchmark รายการ Flexible Points ของบริษัทในอุตสาหกรรมเดียวกันเพิ่มเติม ยินดีส่งให้ทางนี้ได้นะครับ',
        timestamp: '2026-08-23T13:20:00.000Z',
        isStaff: false,
        isReadByEmployee: true,
        isReadByStaff: true,
      },
      {
        id: 'chat-m6',
        ticketId: 'tk-3',
        senderRole: 'gatekeeper',
        senderDisplayName: 'ภานุมาศ สัจจาภิรมย์ (Head of Total Rewards)',
        message:
          'ขอบพระคุณมากครับ ข้อเสนอนี้เป็นประโยชน์ต่อพนักงานทุกคนในองค์กร ทางทีมงานได้สรุปผลและส่งมอบเข้าสู่แผนปี 2027 เรียบร้อยแล้วครับ',
        timestamp: '2026-08-25T14:40:00.000Z',
        isStaff: true,
        isReadByEmployee: true,
        isReadByStaff: true,
      },
    ],
    createdAt: '2026-08-22T10:00:00.000Z',
    updatedAt: '2026-08-26T09:00:00.000Z',
  },
  {
    id: 'tk-4',
    trackingCode: 'TK-2026-0878',
    type: 'complaint',
    category: 'Harassment',
    title: 'การใช้คำพูดคุกคามและข่มขู่ในช่องสื่อสารกลุ่มงาน',
    description:
      'หัวหน้างานระดับกลางใช้ถ้อยคำดูถูกเหยียดหยามและข่มขู่ตัดโบนัสพนักงานต่อหน้าสมาชิกในทีมกว่า 20 คนในแชตกลุ่มงาน สร้างบรรยากาศหวาดกลัวและกระทบต่อสภาพจิตใจของทีม',
    locationOrUnit: 'แผนก Regional Operations สาขาภาคตะวันออก',
    isDirectToExecutive: true,
    confidentiality: 'confidential_restricted',
    submitterName: 'จิรภัทร ชาญวิทย์',
    submitterEmployeeId: 'EMP-3890',
    submitterDepartment: 'Regional Operations',
    submitterEmail: 'jiraphat.c@company.internal',
    gatekeeperDepartment: 'Employee Grievance & Whistleblower Panel',
    assignedOfficerName: 'นิติกรอาวุโส มนตรี ธนบดีกุล (Legal & HR Compliance)',
    assignedOfficerEmail: 'montri.t@company.internal',
    status: 'in_progress',
    urgency: 'High',
    riskSeverity: 'Severe',
    sentiment: 'Frustrated',
    clusterGroup: 'Workplace Psychological Safety & Ethics',
    rootCauseCategory: 'People',
    rootCauseSummary:
      'ภาวะผู้นำบกพร่องและขาดความเข้าใจเรื่อง Anti-Bullying / Harassment Code of Conduct',
    preventiveActionPlan:
      'แต่งตั้งคณะกรรมการสอบข้อเท็จจริงอิสระและจัดคอร์ส Mandatory Respectful Leadership',
    attachments: [
      { id: 'att-6', name: 'chat_export_redacted.pdf', size: '950 KB', type: 'application/pdf' },
    ],
    timeline: [
      {
        id: 'tl-41',
        timestamp: '2026-08-26T16:00:00.000Z',
        actor: 'พนักงาน (ไม่เปิดเผยตัวตน)',
        actorRole: 'Employee',
        action: 'ส่งเรื่องร้องเรียนแบบปกปิดตัวตนพิเศษ',
        status: 'submitted',
        notes: 'เลือกช่องทางส่งตรงถึงผู้บริหารระดับสูง CEO/EVP เพื่อความปลอดภัย',
      },
      {
        id: 'tl-42',
        timestamp: '2026-08-26T17:00:00.000Z',
        actor: 'Whistleblower Triage Committee',
        actorRole: 'Gatekeeper',
        action: 'รับเรื่องและเปิดรหัสสืบสวนลับ',
        status: 'gatekeeper_triaged',
        notes: 'เข้ารหัสข้อมูลผู้ร้องเรียนและมอบหมายนิติกรอาวุโสเป็นผู้รับผิดชอบเดี่ยว',
      },
      {
        id: 'tl-43',
        timestamp: '2026-08-27T08:30:00.000Z',
        actor: 'มนตรี ธนบดีกุล',
        actorRole: 'Assigned Officer',
        action: 'เริ่มกระบวนการสอบข้อเท็จจริงเบื้องต้น',
        status: 'in_progress',
        notes:
          'นัดสัมภาษณ์พยานบุคคลแยกห้องปิด และประสานฝ่ายบุคคลเพื่อพิจารณาการย้ายสายการบังคับบัญชาชั่วคราว',
      },
    ],
    anonymousMessages: [
      {
        id: 'chat-m1',
        ticketId: 'tk-4',
        senderRole: 'gatekeeper',
        senderDisplayName: 'นิติกรอาวุโส มนตรี ธนบดีกุล (Legal & Compliance)',
        message:
          'เรียนผู้ร้องเรียน คณะกรรมการรับทราบข้อร้องเรียนแล้วและกำลังตรวจสอบข้อเท็จจริง ขอความอนุเคราะห์ระบุช่วงเวลาที่เกิดเหตุการณ์ล่าสุดเพื่อประกอบการเทียบเคียงบันทึกสนทนาครับ',
        timestamp: '2026-08-27T09:15:00.000Z',
        isStaff: true,
        isReadByEmployee: true,
        isReadByStaff: true,
      },
      {
        id: 'chat-m2',
        ticketId: 'tk-4',
        senderRole: 'employee',
        senderDisplayName: 'ผู้ร้องเรียน (ไม่เปิดเผยตัวตน / Anonymous)',
        message:
          'เหตุการณ์ล่าสุดเกิดขึ้นเมื่อวันอังคารที่ 25 ส.ค. เวลาประมาณ 15:30 น. ในห้องแชต Regional-All ครับ และมีเพื่อนร่วมงานอีก 2 คนที่อยู่ในเหตุการณ์ด้วยครับ',
        timestamp: '2026-08-27T10:05:00.000Z',
        isStaff: false,
        isReadByEmployee: true,
        isReadByStaff: true,
      },
      {
        id: 'chat-m3',
        ticketId: 'tk-4',
        senderRole: 'gatekeeper',
        senderDisplayName: 'นิติกรอาวุโส มนตรี ธนบดีกุล (Legal & Compliance)',
        message:
          'ขอบพระคุณสำหรับข้อมูลสำคัญครับ ทางทีมงานได้บันทึกเป็นพยานหลักฐานและมีมาตรการคุ้มครองพยานอย่างเคร่งครัด ท่านสามารถแจ้งข้อมูลเพิ่มเติมผ่านช่องทางนี้ได้ตลอดเวลาครับ',
        timestamp: '2026-08-27T10:20:00.000Z',
        isStaff: true,
        isReadByEmployee: true,
        isReadByStaff: true,
      },
    ],
    createdAt: '2026-08-26T16:00:00.000Z',
    updatedAt: '2026-08-27T08:30:00.000Z',
  },
  {
    id: 'tk-5',
    trackingCode: 'TK-2026-0877',
    type: 'complaint',
    category: 'Quality',
    title: 'ระบบปรับอากาศปล่อยน้ำรั่วซึมลงแปลงคัดแยกขยะรีไซเคิล และเปิดแอร์ทิ้งไว้ช่วงวันหยุด',
    description:
      'พบระบบชิลเลอร์ชั้น 4 มีน้ำหยดลงจุดเก็บกล่องกระดาษรีไซเคิลทำให้เน่าเสีย และมีการเปิดเครื่องปรับอากาศทิ้งไว้ในวันเสาร์-อาทิตย์โดยไม่มีการใช้งาน เป็นการสิ้นเปลืองพลังงานขัดต่อนโยบาย ESG',
    locationOrUnit: 'อาคารนวัตกรรม C ชั้น 4',
    isDirectToExecutive: false,
    confidentiality: 'standard_named',
    submitterName: 'ธีรดนย์ สิริพงษ์',
    submitterEmployeeId: 'EMP-5531',
    submitterDepartment: 'Facilities & ESG Sustainability',
    submitterEmail: 'teeradon.s@company.internal',
    gatekeeperDepartment: 'Operational Excellence & Quality Assurance',
    assignedOfficerName: 'ช่างเทคนิค พงศธร เกษมสุข',
    assignedOfficerEmail: 'pongsathorn.k@company.internal',
    status: 'in_progress',
    urgency: 'Medium',
    riskSeverity: 'Low',
    sentiment: 'Concerned',
    clusterGroup: 'Energy Conservation & Facility Maintenance',
    rootCauseCategory: 'Equipment/Tools',
    rootCauseSummary:
      'ท่อระบายน้ำทิ้งคอยล์เย็นอุดตัน และ Timer ระบบ Building Automation System (BAS) รีเซ็ตค่าหลังไฟตก',
    preventiveActionPlan: 'ล้างท่อระบายน้ำและตั้งค่าระบบตั้งเวลาอัตโนมัติบน Cloud BAS',
    attachments: [
      { id: 'att-7', name: 'water_leak_chiller4.jpg', size: '1.5 MB', type: 'image/jpeg' },
    ],
    timeline: [
      {
        id: 'tl-51',
        timestamp: '2026-08-26T10:00:00.000Z',
        actor: 'ธีรดนย์ สิริพงษ์',
        actorRole: 'Employee',
        action: 'ส่งเรื่องแจ้งข้อบกพร่องสิ่งแวดล้อม',
        status: 'submitted',
      },
      {
        id: 'tl-52',
        timestamp: '2026-08-26T11:30:00.000Z',
        actor: 'ESG Gatekeeper',
        actorRole: 'Gatekeeper',
        action: 'รับเรื่องและประสานงานทีมช่างอาคาร',
        status: 'gatekeeper_triaged',
      },
      {
        id: 'tl-53',
        timestamp: '2026-08-26T14:00:00.000Z',
        actor: 'พงศธร เกษมสุข',
        actorRole: 'Assigned Officer',
        action: 'เข้าตรวจสอบท่อแอร์และปรับแก้โปรแกรม BAS',
        status: 'in_progress',
      },
    ],
    createdAt: '2026-08-26T10:00:00.000Z',
    updatedAt: '2026-08-26T14:00:00.000Z',
  },
  {
    id: 'tk-6',
    trackingCode: 'TK-2026-0876',
    type: 'complaint',
    category: 'Fraud',
    title: 'ข้อสงสัยเกี่ยวกับการเสนอราคาคู่เทียบในการจัดซื้ออุปกรณ์ฮาร์ดแวร์พิเศษ',
    description:
      'ตรวจพบว่าใบเสนอราคา 3 บริษัทคู่เทียบมีที่อยู่จดทะเบียนและเบอร์โทรศัพท์เดียวกัน มีแนวโน้มเป็นการจัดฮั้วประมูลเพื่อหลีกเลี่ยงเกณฑ์การตรวจสอบราคากลาง',
    locationOrUnit: 'ฝ่ายจัดซื้อและสัญญา (Procurement)',
    isDirectToExecutive: true,
    confidentiality: 'confidential_restricted',
    submitterName: 'วรัญญู พรหมประสิทธิ์',
    submitterEmployeeId: 'EMP-2914',
    submitterDepartment: 'ฝ่ายจัดซื้อและสัญญา (Procurement)',
    submitterEmail: 'waranyu.p@company.internal',
    gatekeeperDepartment: 'Internal Audit & Forensic Investigation',
    assignedOfficerName: 'วรพจน์ ปิยะปัญญา (Director of Forensic Audit)',
    assignedOfficerEmail: 'worapoj.p@company.internal',
    status: 'in_progress',
    urgency: 'Critical',
    riskSeverity: 'Severe',
    sentiment: 'Urgent',
    clusterGroup: 'Procurement Integrity & Anti-Corruption',
    rootCauseCategory: 'Policy/Governance',
    rootCauseSummary:
      'ขาดระบบตรวจสอบความเชื่อมโยงของผู้ถือหุ้นบริษัทคู่เทียบอัตโนมัติในกระบวนการ Vendor Onboarding',
    preventiveActionPlan:
      'เชื่อมต่อ API กรมพัฒนาธุรกิจการค้า (DBD) เพื่อตรวจเช็ค Cross-Shareholding อัตโนมัติ',
    attachments: [
      {
        id: 'att-8',
        name: 'procurement_quotations_evidence.pdf',
        size: '4.5 MB',
        type: 'application/pdf',
      },
    ],
    timeline: [
      {
        id: 'tl-61',
        timestamp: '2026-08-25T11:00:00.000Z',
        actor: 'ผู้แจ้งเบาะแสไม่ประสงค์ออกนาม',
        actorRole: 'Employee',
        action: 'แจ้งเบาะแสการทุจริตผ่าน Whistleblowing Portal',
        status: 'submitted',
        notes: 'ส่งตรงถึงบอร์ดบริหารและผู้อำนวยการฝ่ายตรวจสอบภายใน',
      },
      {
        id: 'tl-62',
        timestamp: '2026-08-25T11:30:00.000Z',
        actor: 'Internal Audit Gatekeeper',
        actorRole: 'Gatekeeper',
        action: 'รับเรื่องและกำหนดมาตรการคุ้มครองพยาน',
        status: 'gatekeeper_triaged',
      },
      {
        id: 'tl-63',
        timestamp: '2026-08-25T14:00:00.000Z',
        actor: 'วรพจน์ ปิยะปัญญา',
        actorRole: 'Assigned Officer',
        action: 'อายัดเอกสารการจัดซื้อและเริ่มการตรวจสอบเชิงลึก',
        status: 'in_progress',
      },
    ],
    createdAt: '2026-08-25T11:00:00.000Z',
    updatedAt: '2026-08-25T14:00:00.000Z',
  },
  {
    id: 'tk-7',
    trackingCode: 'TK-2026-0875',
    type: 'complaint',
    category: 'Quality',
    title: 'คู่มือการทำงาน (SOP) ในสายการผลิตไลน์ 3 ข้อมูลไม่ตรงกับเครื่องจักรรุ่นใหม่',
    description:
      'เอกสารคู่มือการผลิตและการตรวจสอบคุณภาพที่ติดหน้างานเป็นเวอร์ชันเก่า ทำให้พนักงานใหม่เข้าใจขั้นตอนการสอบเทียบเซนเซอร์ผิดพลาดและเกิดของเสียในล็อตการผลิต',
    locationOrUnit: 'โรงงานผลิต สายการประกอบ 3',
    isDirectToExecutive: false,
    confidentiality: 'standard_named',
    submitterName: 'ณภัทร วัฒนโกสินทร์',
    submitterEmployeeId: 'EMP-4092',
    submitterDepartment: 'Enterprise Solutions Group',
    submitterEmail: 'naphat.w@company.internal',
    gatekeeperDepartment: 'Operational Excellence & Quality Assurance',
    assignedOfficerName: 'วิภาดา พรหมมาศ (QA Specialist)',
    assignedOfficerEmail: 'wiphada.p@company.internal',
    status: 'closed',
    urgency: 'Medium',
    riskSeverity: 'Moderate',
    sentiment: 'Concerned',
    clusterGroup: 'Process Standardization & SOP Maintenance',
    rootCauseCategory: 'Process',
    rootCauseSummary:
      'ฝ่ายวิศวกรรมส่งมอบเครื่องจักรใหม่โดยยังไม่ได้อัปเดตเอกสารมาตรฐาน QA เข้าระบบ Document Control',
    preventiveActionPlan:
      'บังคับใช้ Checklist การตรวจรับเครื่องจักรใหม่ ต้องมี SOP ภาษาไทยอนุมัติก่อนเริ่มการผลิต',
    resolutionSummary:
      'ทีม QA ได้ทำการแก้ไขและพิมพ์ SOP ฉบับอัปเดต Rev.4 พร้อม QR Code วิดีโอสอนการใช้งานติดหน้างานเรียบร้อยแล้ว และจัด Briefing พนักงานประจำกะทุกคน',
    resolvedAt: '2026-08-26T15:00:00.000Z',
    closedAt: '2026-08-27T08:30:00.000Z',
    evaluation: {
      id: 'eval-2',
      ticketId: 'tk-7',
      overallScore: 4,
      speedRating: 4,
      resolutionQualityRating: 5,
      serviceMannerRating: 5,
      clarityRating: 4,
      isResolvedPermanently: true,
      feedbackComment:
        'ทีม QA ดำเนินการแก้ไขได้รวดเร็วมาก มีการทำวิดีโอ QR Code ให้สแกนดูทำให้เข้าใจง่ายขึ้นมากครับ',
      improvementSuggestions: 'อยากให้มีการทบทวน SOP ของไลน์ 1 และ 2 เพิ่มเติมด้วยครับ',
      evaluatedAt: '2026-08-27T08:30:00.000Z',
    },
    attachments: [
      { id: 'att-9', name: 'sop_discrepancy_photo.jpg', size: '1.1 MB', type: 'image/jpeg' },
    ],
    timeline: [
      {
        id: 'tl-71',
        timestamp: '2026-08-24T08:30:00.000Z',
        actor: 'อนุชา รัตนเวช',
        actorRole: 'Employee',
        action: 'ส่งเรื่องแจ้งข้อบกพร่องเอกสาร QA',
        status: 'submitted',
      },
      {
        id: 'tl-72',
        timestamp: '2026-08-24T09:30:00.000Z',
        actor: 'QA Gatekeeper',
        actorRole: 'Gatekeeper',
        action: 'รับเรื่องและอนุมัติใบแจ้งแก้ไขด่วน',
        status: 'gatekeeper_triaged',
      },
      {
        id: 'tl-73',
        timestamp: '2026-08-25T10:00:00.000Z',
        actor: 'วิภาดา พรหมมาศ',
        actorRole: 'Assigned Officer',
        action: 'จัดทำ SOP Rev.4 และทดสอบขั้นตอนจริงหน้างาน',
        status: 'in_progress',
      },
      {
        id: 'tl-74',
        timestamp: '2026-08-26T15:00:00.000Z',
        actor: 'วิภาดา พรหมมาศ',
        actorRole: 'Assigned Officer',
        action: 'ติดตั้ง SOP ใหม่และสรุปผลการแก้ไข',
        status: 'resolved',
      },
      {
        id: 'tl-75',
        timestamp: '2026-08-27T08:30:00.000Z',
        actor: 'อนุชา รัตนเวช',
        actorRole: 'Employee',
        action: 'ประเมินความพึงพอใจ 4 ดาวและปิดเรื่อง',
        status: 'closed',
      },
    ],
    createdAt: '2026-08-24T08:30:00.000Z',
    updatedAt: '2026-08-27T08:30:00.000Z',
  },
  {
    id: 'tk-8',
    trackingCode: 'TK-2026-0874',
    type: 'complaint',
    category: 'Ethics',
    title: 'ข้อร้องเรียนเรื่องการเลือกปฏิบัติในการจัดสรรกะการทำงานล่วงเวลา (OT)',
    description:
      'หัวหน้ากะจัดสรรชั่วโมงโอทีให้เฉพาะกลุ่มคนสนิท ทำให้พนักงานคนอื่นเสียโอกาสในการสร้างรายได้เสริมอย่างไม่เป็นธรรมและขาดความโปร่งใส',
    locationOrUnit: 'ศูนย์กระจายสินค้าภาคกลาง',
    isDirectToExecutive: false,
    confidentiality: 'confidential_restricted',
    submitterName: 'ปวีณา อุดมทรัพย์',
    submitterEmployeeId: 'EMP-3120',
    submitterDepartment: 'Logistics & Supply Chain Operations',
    submitterEmail: 'paweena.u@company.internal',
    gatekeeperDepartment: 'Ethics Committee & Internal Governance',
    assignedOfficerName: 'รพีพร เกียรติภักดี (Employee Relations Specialist)',
    assignedOfficerEmail: 'rapeeporn.k@company.internal',
    status: 'in_progress',
    urgency: 'Medium',
    riskSeverity: 'Moderate',
    sentiment: 'Frustrated',
    clusterGroup: 'Workplace Fairness & Supervisory Conduct',
    rootCauseCategory: 'People',
    rootCauseSummary: 'ไม่มีระบบหมุนเวียนโควตา OT แบบดิจิทัล ใช้ดุลยพินิจของหัวหน้ากะแบบ manual',
    preventiveActionPlan:
      'นำระบบ Auto-OT Allocation ในแอปพลิเคชันพนักงานมาใช้เพื่อความโปร่งใส 100%',
    attachments: [],
    timeline: [
      {
        id: 'tl-81',
        timestamp: '2026-08-26T13:00:00.000Z',
        actor: 'พนักงานผู้ขอสงวนนาม',
        actorRole: 'Employee',
        action: 'ยื่นเรื่องร้องเรียนด้านความเป็นธรรม',
        status: 'submitted',
      },
      {
        id: 'tl-82',
        timestamp: '2026-08-26T15:00:00.000Z',
        actor: 'Ethics Gatekeeper',
        actorRole: 'Gatekeeper',
        action: 'รับเรื่องและตรวจสอบประวัติการลงเวลา OT ย้อนหลัง 3 เดือน',
        status: 'gatekeeper_triaged',
      },
      {
        id: 'tl-83',
        timestamp: '2026-08-27T10:00:00.000Z',
        actor: 'รพีพร เกียรติภักดี',
        actorRole: 'Assigned Officer',
        action: 'เรียกผู้จัดการศูนย์เข้าชี้แจงและตรวจสอบข้อมูลสถิติ',
        status: 'in_progress',
      },
    ],
    createdAt: '2026-08-26T13:00:00.000Z',
    updatedAt: '2026-08-27T10:00:00.000Z',
  },
  {
    id: 'tk-9',
    trackingCode: 'TK-2026-0873',
    type: 'complaint',
    category: 'Compliance',
    title: 'การจัดเก็บข้อมูลลูกค้าบนกระดาษโดยไม่มีการทำลายตามมาตรฐาน PDPA',
    description:
      'พบเอกสารสำเนาบัตรประชาชนและข้อมูลติดต่อของลูกค้าที่ทำธุรกรรมหน้าร้านสาขาวางทิ้งไว้ในกล่องไม่ได้ใส่ตู้ล็อค และยังไม่มีการทำลายตามระยะเวลาที่กำหนดในกฎหมายคุ้มครองข้อมูลส่วนบุคคล',
    locationOrUnit: 'สาขาบริการลูกค้า Central World',
    isDirectToExecutive: true,
    confidentiality: 'standard_named',
    submitterName: 'วิศรุต สุทธิศิริ',
    submitterEmployeeId: 'EMP-7811',
    submitterDepartment: 'Customer Experience & Retail',
    submitterEmail: 'wissarut.s@company.internal',
    gatekeeperDepartment: 'Governance, Risk & Compliance Division',
    assignedOfficerName: 'ธเนศ พงษ์ไพบูลย์ (Data Protection Officer - DPO)',
    assignedOfficerEmail: 'thanet.p@company.internal',
    status: 'resolved',
    urgency: 'High',
    riskSeverity: 'High',
    sentiment: 'Concerned',
    clusterGroup: 'Data Privacy & PDPA Compliance',
    rootCauseCategory: 'Policy/Governance',
    rootCauseSummary: 'สาขาไม่มีเครื่องทำลายเอกสาร (Shredder) ประจำจุด และขาดตู้เซฟเก็บเอกสารสำคัญ',
    preventiveActionPlan:
      'จัดซื้อเครื่องทำลายเอกสาร Cross-Cut ระดับความปลอดภัย DIN Level 4 ประจำทุกสาขา และเปลี่ยนเป็น Digital e-KYC 100%',
    resolutionSummary:
      'DPO ได้ส่งทีมเข้าเก็บรวบรวมเอกสารทั้งหมดนำไปทำลายตามมาตรฐานความปลอดภัย พร้อมติดตั้งตู้ล็อคเอกสาร และเปิดใช้งานระบบ Paperless e-KYC ที่สาขาเพื่อป้องกันข้อมูลรั่วไหลถาวร',
    resolvedAt: '2026-08-27T11:30:00.000Z',
    attachments: [
      { id: 'att-10', name: 'pdpa_paper_storage_log.pdf', size: '2.1 MB', type: 'application/pdf' },
    ],
    timeline: [
      {
        id: 'tl-91',
        timestamp: '2026-08-26T09:00:00.000Z',
        actor: 'วิศรุต สุทธิศิริ',
        actorRole: 'Employee',
        action: 'แจ้งเตือนความเสี่ยงด้าน PDPA ส่งตรงถึงผู้บริหาร',
        status: 'submitted',
      },
      {
        id: 'tl-92',
        timestamp: '2026-08-26T10:00:00.000Z',
        actor: 'Compliance Gatekeeper',
        actorRole: 'Gatekeeper',
        action: 'รับเรื่องและเปิดมาตรการ Data Breach Prevention',
        status: 'gatekeeper_triaged',
      },
      {
        id: 'tl-93',
        timestamp: '2026-08-26T13:00:00.000Z',
        actor: 'ธเนศ พงษ์ไพบูลย์',
        actorRole: 'Assigned Officer',
        action: 'เข้าตรวจค้นและยึดเอกสารเข้าสู่ศูนย์ควบคุมความปลอดภัย',
        status: 'in_progress',
      },
      {
        id: 'tl-94',
        timestamp: '2026-08-27T11:30:00.000Z',
        actor: 'ธเนศ พงษ์ไพบูลย์',
        actorRole: 'Assigned Officer',
        action: 'ดำเนินการทำลายเอกสารและรายงาน DPO ปิดเคสความเสี่ยง',
        status: 'resolved',
      },
    ],
    createdAt: '2026-08-26T09:00:00.000Z',
    updatedAt: '2026-08-27T11:30:00.000Z',
  },
  {
    id: 'tk-11',
    trackingCode: 'TK-2026-0883',
    type: 'complaint',
    category: 'HR',
    title: 'สอบถามความชัดเจนเรื่องสิทธิการเบิกค่ารักษาพยาบาลกรณีพบแพทย์เฉพาะทางนอกเวลา',
    description:
      'เอกสารคู่มือสวัสดิการระบุไม่ชัดเจนเกี่ยวกับการเบิกจ่ายคลินิกพิเศษนอกเวลาของโรงพยาบาลรัฐ ทำให้พนักงานถูกตีกลับเอกสารขอเบิก',
    locationOrUnit: 'Corporate HR Services',
    isDirectToExecutive: false,
    confidentiality: 'standard_named',
    submitterName: 'ชลธิชา รัตนไพบูลย์',
    submitterEmployeeId: 'EMP-1823',
    submitterDepartment: 'Strategic Marketing & Brand',
    submitterEmail: 'chonticha.r@company.internal',
    gatekeeperDepartment: 'People & Culture Department',
    status: 'submitted',
    urgency: 'Medium',
    riskSeverity: 'Low',
    sentiment: 'Concerned',
    clusterGroup: 'Medical Benefits & Policy Clarification',
    rootCauseCategory: 'Policy/Governance',
    rootCauseSummary:
      'คู่มือสวัสดิการไม่ได้ระบุคำนิยามของคลินิกพิเศษนอกเวลาให้ครอบคลุมตามประกาศกระทรวงสาธารณสุขฉบับปรับปรุง',
    preventiveActionPlan:
      'ออกประกาศคำชี้แจงระเบียบการเบิกจ่ายสวัสดิการค่ารักษาพยาบาลฉบับปรับปรุงพร้อม Infographic ให้พนักงานทราบ',
    attachments: [],
    timeline: [
      {
        id: 'tl-111',
        timestamp: '2026-08-31T15:00:00.000Z',
        actor: 'กานต์นภัส รัตนวิบูลย์',
        actorRole: 'Employee',
        action: 'ยื่นคำร้องขอคำชี้แจงระเบียบสวัสดิการ',
        status: 'submitted',
        notes: 'รอฝ่าย HR ประจำแผนกรับเรื่องเพื่อตรวจสอบระเบียบการเบิกจ่าย',
      },
    ],
    createdAt: '2026-08-31T15:00:00.000Z',
    updatedAt: '2026-08-31T15:00:00.000Z',
  },
  {
    id: 'tk-12',
    trackingCode: 'TK-2026-0884',
    type: 'suggestion',
    category: 'HR',
    title: 'ข้อเสนอแนะ: ขยายเวลาเปิดให้บริการห้องพยาบาลประจำโรงงานช่วงกะดึก',
    description:
      'พนักงานฝ่ายผลิตกะดึก (20:00 - 08:00) ขอเสนอให้มีพยาบาลวิชาชีพหรือเจ้าหน้าที่ปฐมพยาบาลประจำการตลอด 24 ชั่วโมง เพื่อรองรับเหตุเจ็บป่วยฉุกเฉิน',
    locationOrUnit: 'โรงงานระยอง โซนพยาบาลอาคาร 1',
    isDirectToExecutive: false,
    confidentiality: 'standard_named',
    submitterName: 'พิเชษฐ์ เลิศวณิชย์',
    submitterEmployeeId: 'EMP-5512',
    submitterDepartment: 'Plant Operations & Manufacturing',
    submitterEmail: 'pichet.l@company.internal',
    gatekeeperDepartment: 'People & Culture Department',
    status: 'submitted',
    urgency: 'Medium',
    riskSeverity: 'Moderate',
    sentiment: 'Constructive',
    clusterGroup: 'Employee Health & Clinic Accessibility',
    rootCauseCategory: 'Process',
    rootCauseSummary:
      'สัญญาจัดจ้างบุคลากรทางการแพทย์เดิมครอบคลุมเฉพาะกะกลางวัน ยังไม่ได้ขยายขอบเขตสู่กะทำงาน 24 ชั่วโมง',
    preventiveActionPlan:
      'ประสานงานโรงพยาบาลคู่สัญญาจัดส่งพยาบาลเวรปฏิบัติงานกะดึก และติดตั้งกล่องปฐมพยาบาลอัตโนมัติประจำสายการผลิต',
    attachments: [],
    timeline: [
      {
        id: 'tl-121',
        timestamp: '2026-08-31T16:10:00.000Z',
        actor: 'พิเชษฐ์ เลิศวณิชย์',
        actorRole: 'Employee',
        action: 'ยื่นข้อเสนอแนะพัฒนาห้องพยาบาล',
        status: 'submitted',
      },
    ],
    createdAt: '2026-08-31T16:10:00.000Z',
    updatedAt: '2026-08-31T16:10:00.000Z',
  },
  {
    id: 'tk-14',
    trackingCode: 'TK-2026-0886',
    type: 'complaint',
    category: 'Compliance',
    title: 'ข้อหารือเรื่องแนวปฏิบัติการส่งข้อมูลพนักงานให้คู่ค้าภายนอกตามเกณฑ์ PDPA',
    description:
      'ฝ่ายการตลาดต้องการส่งรายชื่อผู้ร่วมงานสัมมนาให้ผู้จัดงานภายนอก ขอคำแนะนำและแบบฟอร์ม Data Sharing Agreement',
    locationOrUnit: 'ฝ่ายการตลาดและการสื่อสารองค์กร',
    isDirectToExecutive: false,
    confidentiality: 'standard_named',
    submitterName: 'ณภัทร วัฒนโกสินทร์',
    submitterEmployeeId: 'EMP-4092',
    submitterDepartment: 'Enterprise Solutions Group',
    submitterEmail: 'naphat.w@company.internal',
    gatekeeperDepartment: 'Governance, Risk & Compliance Division',
    status: 'submitted',
    urgency: 'Medium',
    riskSeverity: 'Low',
    sentiment: 'Constructive',
    clusterGroup: 'Data Sharing Agreements & PDPA Compliance',
    rootCauseCategory: 'Policy/Governance',
    rootCauseSummary:
      'ยังไม่มี Template ข้อตกลงประมวลผลข้อมูล (Data Processing Agreement) สำเร็จรูปบนระบบเอกสารส่วนกลาง',
    preventiveActionPlan:
      'จัดทำ DPA Standard Template และจัดอบรมกระบวนการเปิดเผยข้อมูลส่วนบุคคลภายนอกแก่องค์กร',
    attachments: [],
    timeline: [
      {
        id: 'tl-141',
        timestamp: '2026-08-31T18:00:00.000Z',
        actor: 'ปวีณ์กร มิ่งขวัญ',
        actorRole: 'Employee',
        action: 'ยื่นคำขอรับคำปรึกษาด้านกฎเกณฑ์',
        status: 'submitted',
      },
    ],
    createdAt: '2026-08-31T18:00:00.000Z',
    updatedAt: '2026-08-31T18:00:00.000Z',
  },
  {
    id: 'tk-15',
    trackingCode: 'TK-2026-0887',
    type: 'complaint',
    category: 'Ethics',
    title:
      'ข้อร้องเรียนเรื่องการรับของขวัญมูลค่าสูงและเลี้ยงสังสรรค์ช่วงเทศกาลจากคู่ค้าผู้ประมูลงาน',
    description:
      'พบข้อมูลว่ามีกรรมการตรวจรับงานเข้าร่วมงานเลี้ยงสังสรรค์ส่วนตัวที่จัดโดยผู้รับเหมารายใหญ่ที่อยู่ระหว่างขั้นตอนการประมูลคัดเลือก',
    locationOrUnit: 'ฝ่ายจัดซื้อและวิศวกรรมโครงการ',
    isDirectToExecutive: true,
    confidentiality: 'confidential_restricted',
    submitterName: 'พนักงานผู้แจ้งเบาะแส (ไม่เปิดเผยชื่อ)',
    gatekeeperDepartment: 'Ethics Committee & Internal Governance',
    status: 'submitted',
    urgency: 'Critical',
    riskSeverity: 'Severe',
    sentiment: 'Urgent',
    clusterGroup: 'Conflict of Interest & Gift Policy Violation',
    rootCauseCategory: 'People',
    rootCauseSummary:
      'กรรมการตรวจรับงานบางรายขาดความตระหนักเรื่องนโยบาย No-Gift Policy และความขัดแย้งทางผลประโยชน์ (Conflict of Interest)',
    preventiveActionPlan:
      'จัดทำแบบฟอร์ม Conflict of Interest Declaration ภาคบังคับก่อนเปิดซองประมูล และสับเปลี่ยนคณะกรรมการตรวจรับ',
    attachments: [],
    timeline: [
      {
        id: 'tl-151',
        timestamp: '2026-08-31T19:15:00.000Z',
        actor: 'ผู้แจ้งเบาะแส',
        actorRole: 'Employee',
        action: 'แจ้งเบาะแสจริยธรรมส่งตรงถึง CEO/EVP',
        status: 'submitted',
        notes: 'เลือกช่องทางส่งตรง CEO เนื่องจากผู้ถูกร้องเป็นหัวหน้าแผนก',
      },
    ],
    createdAt: '2026-08-31T19:15:00.000Z',
    updatedAt: '2026-08-31T19:15:00.000Z',
  },
  {
    id: 'tk-16',
    trackingCode: 'TK-2026-0888',
    type: 'complaint',
    category: 'Harassment',
    title: 'พฤติกรรมการใช้วาจาข่มขู่คุกคามและการเลือกปฏิบัติในแผนกงานอย่างต่อเนื่อง',
    description:
      'พนักงานในทีมถูกผู้จัดการกดดันด้วยถ้อยคำหยาบคาย และข่มขู่ว่าจะไม่ผ่านการทดลองงานหากไม่ยอมทำงานนอกเวลาโดยไม่บันทึกโอที',
    locationOrUnit: 'ศูนย์กระจายสินค้าภาคตะวันออกเฉียงเหนือ',
    isDirectToExecutive: true,
    confidentiality: 'confidential_restricted',
    submitterName: 'พนักงานผู้ได้รับผลกระทบ',
    gatekeeperDepartment: 'Employee Grievance & Whistleblower Panel',
    status: 'submitted',
    urgency: 'Critical',
    riskSeverity: 'Severe',
    sentiment: 'Frustrated',
    clusterGroup: 'Workplace Psychological Safety & Anti-Bullying',
    rootCauseCategory: 'People',
    rootCauseSummary:
      'ผู้จัดการแผนกใช้อำนาจเกินขอบเขตและขาดทักษะการสื่อสารเชิงสร้างสรรค์ ส่งผลกระทบต่อจิตวิทยาการทำงานของทีมงาน',
    preventiveActionPlan:
      'ดำเนินการสอบสวนทางวินัยทันที ให้พักการปฏิบัติหน้าที่การบังคับบัญชา และจัดหลักสูตร People Management สำหรับหัวหน้างาน',
    attachments: [],
    timeline: [
      {
        id: 'tl-161',
        timestamp: '2026-08-31T20:00:00.000Z',
        actor: 'ผู้ร้องเรียน',
        actorRole: 'Employee',
        action: 'ยื่นคำร้องเรียนฉุกเฉินส่งตรงคณะกรรมการคุ้มครองสิทธิ์',
        status: 'submitted',
      },
    ],
    createdAt: '2026-08-31T20:00:00.000Z',
    updatedAt: '2026-08-31T20:00:00.000Z',
  },
  {
    id: 'tk-17',
    trackingCode: 'TK-2026-0889',
    type: 'complaint',
    category: 'Fraud',
    title: 'ข้อสงสัยเกี่ยวกับการอนุมัติเบิกจ่ายค่าเดินทางและเบี้ยเลี้ยงซ้ำซ้อนในโครงการต่างจังหวัด',
    description:
      'ตรวจสอบพบใบเสร็จค่าน้ำมันและโรงแรมที่ซ้ำกับใบเบิกของอีกทีมในวันและเวลาเดียวกัน ยอดรวมกว่า 180,000 บาท',
    locationOrUnit: 'ฝ่ายบริหารโครงการภาคเหนือ',
    isDirectToExecutive: true,
    confidentiality: 'confidential_restricted',
    submitterName: 'ผู้ตรวจสอบภายใน',
    gatekeeperDepartment: 'Internal Audit & Forensic Investigation',
    status: 'submitted',
    urgency: 'Critical',
    riskSeverity: 'Severe',
    sentiment: 'Urgent',
    clusterGroup: 'Expense Claim Integrity & Fraud Audit',
    rootCauseCategory: 'Policy/Governance',
    rootCauseSummary:
      'ระบบอนุมัติเอกสารเบิกจ่ายยังไม่อัลกอริทึมตรวจสอบเลขที่ใบเสร็จหรือวันที่ซ้ำข้ามแผนกในระบบ e-Claim',
    preventiveActionPlan:
      'เปิดระบบ Duplicate Receipt Detection บนระบบเบิกเงิน และตั้งคณะกรรมการตรวจสอบข้อเท็จจริงเพื่อระงับการจ่าย',
    attachments: [],
    timeline: [
      {
        id: 'tl-171',
        timestamp: '2026-08-31T21:10:00.000Z',
        actor: 'ผู้แจ้งเบาะแส',
        actorRole: 'Employee',
        action: 'ส่งเรื่องแจ้งข้อสงสัยทุจริตตรงถึงบอร์ดบริหาร',
        status: 'submitted',
      },
    ],
    createdAt: '2026-08-31T21:10:00.000Z',
    updatedAt: '2026-08-31T21:10:00.000Z',
  },
  {
    id: 'tk-18',
    trackingCode: 'TK-2026-0890',
    type: 'complaint',
    category: 'Quality',
    title: 'อุปกรณ์ตรวจวัด Caliper ในแผนก QA ไลน์ 2 มีค่าเบี่ยงเบนเกินเกณฑ์มาตรฐาน ISO',
    description:
      'อุปกรณ์เวอร์เนียร์คาลิปเปอร์ 4 ตัวที่ใช้ในไลน์ตรวจสอบชิ้นงานแม่พิมพ์ส่งผลการวัดคลาดเคลื่อน 0.05 mm จำเป็นต้องส่งสอบเทียบด่วน',
    locationOrUnit: 'โรงงานแปรรูปชิ้นส่วน ไลน์ QC-02',
    isDirectToExecutive: false,
    confidentiality: 'standard_named',
    submitterName: 'ณภัทร วัฒนโกสินทร์',
    submitterEmployeeId: 'EMP-4092',
    submitterDepartment: 'Enterprise Solutions Group',
    submitterEmail: 'naphat.w@company.internal',
    gatekeeperDepartment: 'Operational Excellence & Quality Assurance',
    status: 'submitted',
    urgency: 'High',
    riskSeverity: 'Moderate',
    sentiment: 'Concerned',
    clusterGroup: 'Calibration & Measurement Tool Accuracy',
    rootCauseCategory: 'Equipment/Tools',
    rootCauseSummary:
      'พ้นกำหนดรอบการสอบเทียบ (Calibration Due Date) โดยไม่มีระบบแจ้งเตือนอัตโนมัติก่อนเครื่องมือหมดอายุการใช้งาน',
    preventiveActionPlan:
      'ติดแถบสีสัญลักษณ์และระบบ RFID แจ้งเตือนรอบสอบเทียบเครื่องมือวัดล่วงหน้า 30 วัน',
    attachments: [],
    timeline: [
      {
        id: 'tl-181',
        timestamp: '2026-08-31T21:40:00.000Z',
        actor: 'สมชาย บุญชู',
        actorRole: 'Employee',
        action: 'ส่งแจ้งเตือนเครื่องมือวัดไม่ได้มาตรฐาน',
        status: 'submitted',
      },
    ],
    createdAt: '2026-08-31T21:40:00.000Z',
    updatedAt: '2026-08-31T21:40:00.000Z',
  },
  {
    id: 'tk-19',
    trackingCode: 'TK-2026-0891',
    type: 'complaint',
    category: 'Compliance',
    title: 'ปัญหากลิ่นสารเคมีและเสียงรบกวนจากบ่อบำบัดน้ำเสียส่วนขยายใกล้โซนโรงอาหาร',
    description:
      'ช่วงเวลา 11:30 - 13:00 น. มีกลิ่นกำมะถันรุนแรงพัดเข้ามายังโรงอาหารพนักงาน ขอให้ฝ่ายตรวจสอบปฏิบัติตามมาตรฐานกฎหมายสิ่งแวดล้อมตรวจเช็คระบบ Bio-filter และพัดลมดูดอากาศ',
    locationOrUnit: 'โรงอาหารกลาง และบ่อบำบัดน้ำเสียแปลงใต้',
    isDirectToExecutive: false,
    confidentiality: 'standard_named',
    submitterName: 'วาสนา กลิ่นสุคนธ์',
    submitterEmployeeId: 'EMP-3318',
    submitterDepartment: 'Administrative Services',
    submitterEmail: 'wassana.k@company.internal',
    gatekeeperDepartment: 'Governance, Risk & Compliance Division',
    status: 'submitted',
    urgency: 'Medium',
    riskSeverity: 'Moderate',
    sentiment: 'Frustrated',
    clusterGroup: 'Odor Control & Wastewater Treatment System',
    rootCauseCategory: 'Workplace/Facilities',
    rootCauseSummary:
      'ระบบเติมอากาศ (Aeration Blower) ของบ่อบำบัดแอนแอโรบิกมีประสิทธิภาพลดลงเนื่องจากวาล์วระบายอากาศตัน',
    preventiveActionPlan:
      'เปลี่ยนหัวจ่ายฟองอากาศ Fine Bubble Diffuser ใหม่ และปลูกแนวไม้ทรงสูงเพื่อเป็น Buffer Zone ดักจับกลิ่น',
    attachments: [],
    timeline: [
      {
        id: 'tl-191',
        timestamp: '2026-08-31T22:00:00.000Z',
        actor: 'วาสนา กลิ่นสุคนธ์',
        actorRole: 'Employee',
        action: 'ส่งเรื่องร้องเรียนกลิ่นรบกวนโรงอาหาร',
        status: 'submitted',
      },
    ],
    createdAt: '2026-08-31T22:00:00.000Z',
    updatedAt: '2026-08-31T22:00:00.000Z',
  },
];

export const INITIAL_GATEKEEPER_CONFIGS: Record<GrievanceCategory, DepartmentGatekeeperConfig> = {
  HR: {
    category: 'HR',
    departmentName: 'People & Culture Department (ฝ่ายบริหารทรัพยากรบุคคล)',
    departmentCode: 'DEPT-HR-01',
    leadOfficer: {
      id: 'usr-hr-1',
      name: 'ชลธิชา เกียรติวรานนท์',
      email: 'chonthicha.k@company.internal',
      roleTitle: 'Head of People Partnering & ER',
      isLead: true,
      phone: '02-555-1101',
    },
    officers: [
      {
        id: 'usr-hr-1',
        name: 'ชลธิชา เกียรติวรานนท์',
        email: 'chonthicha.k@company.internal',
        roleTitle: 'Head of People Partnering & ER',
        isLead: true,
        phone: '02-555-1101',
      },
      {
        id: 'usr-hr-2',
        name: 'รพีพร เกียรติภักดี',
        email: 'rapeeporn.k@company.internal',
        roleTitle: 'Employee Relations Specialist',
        isLead: false,
        phone: '02-555-1102',
      },
      {
        id: 'usr-hr-3',
        name: 'ธนกฤต สิทธิพงศ์',
        email: 'thanakrit.s@company.internal',
        roleTitle: 'Talent & Compensation Lead',
        isLead: false,
        phone: '02-555-1103',
      },
    ],
    autoAssignMode: 'round_robin',
    escalationEmail: 'hr.escalation@company.internal',
    updatedAt: '2026-08-25T10:00:00.000Z',
  },
  Compliance: {
    category: 'Compliance',
    departmentName: 'Governance, Risk & Compliance Division (ฝ่ายกำกับดูแลและกฎหมาย)',
    departmentCode: 'DEPT-GRC-04',
    leadOfficer: {
      id: 'usr-grc-1',
      name: 'กานต์รวี ธรรมศาสตร์',
      email: 'karnrawee.t@company.internal',
      roleTitle: 'Data Protection Officer (DPO) & Legal Lead',
      isLead: true,
      phone: '02-555-4401',
    },
    officers: [
      {
        id: 'usr-grc-1',
        name: 'กานต์รวี ธรรมศาสตร์',
        email: 'karnrawee.t@company.internal',
        roleTitle: 'Data Protection Officer (DPO) & Legal Lead',
        isLead: true,
        phone: '02-555-4401',
      },
      {
        id: 'usr-grc-2',
        name: 'นิติกรอาวุโส มนตรี ธนบดีกุล',
        email: 'montri.t@company.internal',
        roleTitle: 'Senior Legal & Regulatory Counsel',
        isLead: false,
        phone: '02-555-4402',
      },
    ],
    autoAssignMode: 'lead_manual',
    escalationEmail: 'dpo.compliance@company.internal',
    updatedAt: '2026-08-25T11:00:00.000Z',
  },
  Ethics: {
    category: 'Ethics',
    departmentName: 'Ethics Committee & Internal Governance (คณะกรรมการจริยธรรมองค์กร)',
    departmentCode: 'DEPT-ETH-05',
    leadOfficer: {
      id: 'usr-eth-1',
      name: 'ศ.พิเศษ พิทักษ์ สัตยบุตร',
      email: 'pitak.s@company.internal',
      roleTitle: 'Chair of Ethics Review Board',
      isLead: true,
      phone: '02-555-5501',
    },
    officers: [
      {
        id: 'usr-eth-1',
        name: 'ศ.พิเศษ พิทักษ์ สัตยบุตร',
        email: 'pitak.s@company.internal',
        roleTitle: 'Chair of Ethics Review Board',
        isLead: true,
        phone: '02-555-5501',
      },
      {
        id: 'usr-eth-2',
        name: 'นภาพร วรวิทย์',
        email: 'naphaporn.w@company.internal',
        roleTitle: 'Ethics Officer & Ombudsman Secretarial',
        isLead: false,
        phone: '02-555-5502',
      },
    ],
    autoAssignMode: 'lead_manual',
    escalationEmail: 'ethics.board@company.internal',
    updatedAt: '2026-08-20T09:00:00.000Z',
  },
  Fraud: {
    category: 'Fraud',
    departmentName: 'Internal Audit & Forensic Investigation (ฝ่ายตรวจสอบภายในและการสอบสวนทุจริต)',
    departmentCode: 'DEPT-AUD-07',
    leadOfficer: {
      id: 'usr-aud-1',
      name: 'วรพจน์ ปิยะปัญญา',
      email: 'worapoj.p@company.internal',
      roleTitle: 'Director of Forensic Audit & Financial Investigation',
      isLead: true,
      phone: '02-555-7701',
    },
    officers: [
      {
        id: 'usr-aud-1',
        name: 'วรพจน์ ปิยะปัญญา',
        email: 'worapoj.p@company.internal',
        roleTitle: 'Director of Forensic Audit & Financial Investigation',
        isLead: true,
        phone: '02-555-7701',
      },
      {
        id: 'usr-aud-2',
        name: 'ธีรดนย์ รัตนเมธา',
        email: 'theeradon.r@company.internal',
        roleTitle: 'Senior Financial Auditor (CIA, CFE)',
        isLead: false,
        phone: '02-555-7702',
      },
    ],
    autoAssignMode: 'lead_manual',
    escalationEmail: 'forensic.audit@company.internal',
    updatedAt: '2026-08-27T08:00:00.000Z',
  },
  Harassment: {
    category: 'Harassment',
    departmentName:
      'Human Rights & Grievance Panel (คณะกรรมการคุ้มครองสิทธิมนุษยชนและการล่วงละเมิด)',
    departmentCode: 'DEPT-HRM-06',
    leadOfficer: {
      id: 'usr-hrm-1',
      name: 'มนตรี ธนบดีกุล',
      email: 'montri.t@company.internal',
      roleTitle: 'Senior Legal & Whistleblower Protection Lead',
      isLead: true,
      phone: '02-555-6601',
    },
    officers: [
      {
        id: 'usr-hrm-1',
        name: 'มนตรี ธนบดีกุล',
        email: 'montri.t@company.internal',
        roleTitle: 'Senior Legal & Whistleblower Protection Lead',
        isLead: true,
        phone: '02-555-6601',
      },
      {
        id: 'usr-hrm-2',
        name: 'พญ. พรรณนิภา จิตตพัฒน์',
        email: 'phannipha.j@company.internal',
        roleTitle: 'Corporate Psychologist & Counselor',
        isLead: false,
        phone: '02-555-6602',
      },
    ],
    autoAssignMode: 'lead_manual',
    escalationEmail: 'whistleblower.safe@company.internal',
    updatedAt: '2026-08-26T16:00:00.000Z',
  },
  Quality: {
    category: 'Quality',
    departmentName:
      'Operational Excellence & Quality Assurance (ฝ่ายตรวจสอบคุณภาพและมาตรฐาน - Quality Impropriety)',
    departmentCode: 'DEPT-QA-08',
    leadOfficer: {
      id: 'usr-qa-1',
      name: 'วิศรุต สินธพวัฒน์',
      email: 'wisarut.s@company.internal',
      roleTitle: 'Quality Assurance & Lean Process Manager',
      isLead: true,
      phone: '02-555-8801',
    },
    officers: [
      {
        id: 'usr-qa-1',
        name: 'วิศรุต สินธพวัฒน์',
        email: 'wisarut.s@company.internal',
        roleTitle: 'Quality Assurance & Lean Process Manager',
        isLead: true,
        phone: '02-555-8801',
      },
      {
        id: 'usr-qa-2',
        name: 'นลินี วรพงษ์',
        email: 'nalinee.w@company.internal',
        roleTitle: 'Service Quality Auditor',
        isLead: false,
        phone: '02-555-8802',
      },
    ],
    autoAssignMode: 'round_robin',
    escalationEmail: 'qa.feedback@company.internal',
    updatedAt: '2026-08-23T10:00:00.000Z',
  },
};

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    ticketId: 'tk-2',
    trackingCode: 'TK-2026-0880',
    title: 'แก้ไขเสร็จสิ้น: ปัญหาบันไดหนีไฟฉุกเฉิน',
    message:
      'หน่วยงาน EHS ได้ทำการเคลียร์สิ่งกีดขวางเรียบร้อยแล้ว กรุณาเข้าประเมินความพึงพอใจการให้บริการ',
    timestamp: '2026-08-27T15:45:00.000Z',
    read: false,
    type: 'satisfaction_pending',
    recipientRole: 'employee',
  },
  {
    id: 'notif-2',
    ticketId: 'tk-1',
    trackingCode: 'TK-2026-0881',
    title: 'อัปเดตสถานะ: ปัญหาเครือข่าย Wi-Fi ชั้น 18',
    message:
      'วิศวกรโครงข่ายไอที (กิตติศักดิ์ ชัยชนะ) เริ่มเข้าดำเนินการตรวจสอบและปรับแต่ง Access Point แล้ว',
    timestamp: '2026-08-27T13:00:00.000Z',
    read: false,
    type: 'status_update',
    recipientRole: 'employee',
  },
  {
    id: 'notif-3',
    ticketId: 'tk-4',
    trackingCode: 'TK-2026-0878',
    title: 'แจ้งเตือนผู้บริหาร: ได้รับข้อร้องเรียนส่งตรงถึง CEO/EVP',
    message:
      'มีข้อร้องเรียนหมวดหมู่ Harassment ระดับความเร่งด่วนสูง ยื่นเรื่องส่งตรงถึงผู้บริหารระดับสูง',
    timestamp: '2026-08-26T16:00:00.000Z',
    read: true,
    type: 'direct_ceo_alert',
    recipientRole: 'executive',
  },
  {
    id: 'notif-4',
    ticketId: 'tk-9',
    trackingCode: 'TK-2026-0873',
    title: 'แก้ไขเสร็จสิ้น: รายงานความเสี่ยง PDPA สาขา Central World',
    message: 'ฝ่าย Compliance & DPO ได้แก้ไขและทำลายเอกสารเสร็จสมบูรณ์แล้ว',
    timestamp: '2026-08-27T11:30:00.000Z',
    read: true,
    type: 'status_update',
    recipientRole: 'employee',
  },
];
