// Static image imports (e.g. src/app/login/login-hero.webp) need Next's image module types.
// next-env.d.ts carries them but is generated by `next dev/build` and gitignored, and CI runs
// `tsc --noEmit` before `next build` — so they are referenced from this committed file too.
/// <reference types="next/image-types/global" />
